/**
 *
 * $Id$
 */
package org.open.oasis.docs.ns.opencsa.sca.sca.validation;

import org.eclipse.emf.common.util.EList;

import org.open.oasis.docs.ns.opencsa.sca.sca.DeployableType;

/**
 * A sample validator interface for {@link org.open.oasis.docs.ns.opencsa.sca.sca.ContributionType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContributionTypeValidator {
	boolean validate();

	boolean validateDeployable(EList<DeployableType> value);
}
