/**
 *
 * $Id$
 */
package org.open.oasis.docs.ns.opencsa.sca.sca.validation;

import java.util.List;

import org.open.oasis.docs.ns.opencsa.sca.sca.Multiplicity;

/**
 * A sample validator interface for {@link org.open.oasis.docs.ns.opencsa.sca.sca.Reference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReferenceValidator {
	boolean validate();

	boolean validateMultiplicity(Multiplicity value);
	boolean validatePromote(List<String> value);
}
