/**
 *
 * $Id$
 */
package org.open.oasis.docs.ns.opencsa.sca.sca.validation;

import javax.xml.namespace.QName;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link org.open.oasis.docs.ns.opencsa.sca.sca.SCAPropertyBase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SCAPropertyBaseValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateAny(FeatureMap value);
	boolean validateName(String value);
	boolean validateType(QName value);
	boolean validateAnyAttribute(FeatureMap value);
}
