/**
 *
 * $Id$
 */
package org.w3._2001.xml.xsd.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.w3._2001.xml.xsd.AppinfoType;
import org.w3._2001.xml.xsd.DocumentationType;

/**
 * A sample validator interface for {@link org.w3._2001.xml.xsd.AnnotationType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnnotationTypeValidator {
	boolean validate();

	boolean validateGroup(FeatureMap value);
	boolean validateAppinfo(EList<AppinfoType> value);
	boolean validateDocumentation(EList<DocumentationType> value);
	boolean validateId(String value);
}
