/**
 *
 * $Id$
 */
package org.w3._2001.xml.xsd.validation;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link org.w3._2001.xml.xsd.AppinfoType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AppinfoTypeValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateGroup(FeatureMap value);
	boolean validateAny(FeatureMap value);
	boolean validateSource(String value);
	boolean validateAnyAttribute(FeatureMap value);
}
