/**
 *
 * $Id$
 */
package org.w3._2001.xml.xsd.validation;

import javax.xml.namespace.QName;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.w3._2001.xml.xsd.Attribute;
import org.w3._2001.xml.xsd.AttributeGroupRef;
import org.w3._2001.xml.xsd.Wildcard;

/**
 * A sample validator interface for {@link org.w3._2001.xml.xsd.AttributeGroup}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeGroupValidator {
	boolean validate();

	boolean validateGroup(FeatureMap value);
	boolean validateAttribute(EList<Attribute> value);
	boolean validateAttributeGroup(EList<AttributeGroupRef> value);
	boolean validateAnyAttribute1(Wildcard value);
	boolean validateName(String value);
	boolean validateRef(QName value);
}
