/**
 *
 * $Id$
 */
package org.w3._2001.xml.xsd.validation;

import org.eclipse.emf.common.util.EMap;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.w3._2001.xml.xsd.All;
import org.w3._2001.xml.xsd.AnnotationType;
import org.w3._2001.xml.xsd.AnyType;
import org.w3._2001.xml.xsd.AppinfoType;
import org.w3._2001.xml.xsd.ComplexContentType;
import org.w3._2001.xml.xsd.DocumentationType;
import org.w3._2001.xml.xsd.ExplicitGroup;
import org.w3._2001.xml.xsd.Facet;
import org.w3._2001.xml.xsd.FieldType;
import org.w3._2001.xml.xsd.ImportType;
import org.w3._2001.xml.xsd.IncludeType;
import org.w3._2001.xml.xsd.Keybase;
import org.w3._2001.xml.xsd.KeyrefType;
import org.w3._2001.xml.xsd.ListType;
import org.w3._2001.xml.xsd.NamedAttributeGroup;
import org.w3._2001.xml.xsd.NamedGroup;
import org.w3._2001.xml.xsd.NoFixedFacet;
import org.w3._2001.xml.xsd.NotationType;
import org.w3._2001.xml.xsd.NumFacet;
import org.w3._2001.xml.xsd.PatternType;
import org.w3._2001.xml.xsd.RedefineType;
import org.w3._2001.xml.xsd.RestrictionType1;
import org.w3._2001.xml.xsd.SchemaType;
import org.w3._2001.xml.xsd.SelectorType;
import org.w3._2001.xml.xsd.SimpleContentType;
import org.w3._2001.xml.xsd.TopLevelAttribute;
import org.w3._2001.xml.xsd.TopLevelComplexType;
import org.w3._2001.xml.xsd.TopLevelElement;
import org.w3._2001.xml.xsd.TopLevelSimpleType;
import org.w3._2001.xml.xsd.TotalDigitsType;
import org.w3._2001.xml.xsd.UnionType;
import org.w3._2001.xml.xsd.WhiteSpaceType;
import org.w3._2001.xml.xsd.Wildcard;

/**
 * A sample validator interface for {@link org.w3._2001.xml.xsd.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateXMLNSPrefixMap(EMap<String, String> value);
	boolean validateXSISchemaLocation(EMap<String, String> value);
	boolean validateAll(All value);
	boolean validateAnnotation(AnnotationType value);
	boolean validateAny(AnyType value);
	boolean validateAnyAttribute(Wildcard value);
	boolean validateAppinfo(AppinfoType value);
	boolean validateAttribute(TopLevelAttribute value);
	boolean validateAttributeGroup(NamedAttributeGroup value);
	boolean validateChoice(ExplicitGroup value);
	boolean validateComplexContent(ComplexContentType value);
	boolean validateComplexType(TopLevelComplexType value);
	boolean validateDocumentation(DocumentationType value);
	boolean validateElement(TopLevelElement value);
	boolean validateEnumeration(NoFixedFacet value);
	boolean validateField(FieldType value);
	boolean validateFractionDigits(NumFacet value);
	boolean validateGroup(NamedGroup value);
	boolean validateImport(ImportType value);
	boolean validateInclude(IncludeType value);
	boolean validateKey(Keybase value);
	boolean validateKeyref(KeyrefType value);
	boolean validateLength(NumFacet value);
	boolean validateList(ListType value);
	boolean validateMaxExclusive(Facet value);
	boolean validateMaxInclusive(Facet value);
	boolean validateMaxLength(NumFacet value);
	boolean validateMinExclusive(Facet value);
	boolean validateMinInclusive(Facet value);
	boolean validateMinLength(NumFacet value);
	boolean validateNotation(NotationType value);
	boolean validatePattern(PatternType value);
	boolean validateRedefine(RedefineType value);
	boolean validateRestriction(RestrictionType1 value);
	boolean validateSchema(SchemaType value);
	boolean validateSelector(SelectorType value);
	boolean validateSequence(ExplicitGroup value);
	boolean validateSimpleContent(SimpleContentType value);
	boolean validateSimpleType(TopLevelSimpleType value);
	boolean validateTotalDigits(TotalDigitsType value);
	boolean validateUnion(UnionType value);
	boolean validateUnique(Keybase value);
	boolean validateWhiteSpace(WhiteSpaceType value);
}
