/**
 *
 * $Id$
 */
package org.w3._2001.xml.xsd.validation;

import org.w3._2001.xml.xsd.All;
import org.w3._2001.xml.xsd.ExplicitGroup;

/**
 * A sample validator interface for {@link org.w3._2001.xml.xsd.RealGroup}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RealGroupValidator {
	boolean validate();

	boolean validateAll1(All value);
	boolean validateChoice1(ExplicitGroup value);
	boolean validateSequence1(ExplicitGroup value);
}
