/**
 *
 * $Id$
 */
package org.w3._2001.xml.xsd.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.w3._2001.xml.xsd.AnnotationType;
import org.w3._2001.xml.xsd.FormChoice;
import org.w3._2001.xml.xsd.ImportType;
import org.w3._2001.xml.xsd.IncludeType;
import org.w3._2001.xml.xsd.NamedAttributeGroup;
import org.w3._2001.xml.xsd.NamedGroup;
import org.w3._2001.xml.xsd.NotationType;
import org.w3._2001.xml.xsd.RedefineType;
import org.w3._2001.xml.xsd.TopLevelAttribute;
import org.w3._2001.xml.xsd.TopLevelComplexType;
import org.w3._2001.xml.xsd.TopLevelElement;
import org.w3._2001.xml.xsd.TopLevelSimpleType;

/**
 * A sample validator interface for {@link org.w3._2001.xml.xsd.SchemaType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SchemaTypeValidator {
	boolean validate();

	boolean validateGroup(FeatureMap value);
	boolean validateInclude(EList<IncludeType> value);
	boolean validateImport(EList<ImportType> value);
	boolean validateRedefine(EList<RedefineType> value);
	boolean validateAnnotation(EList<AnnotationType> value);
	boolean validateGroup1(FeatureMap value);
	boolean validateSimpleType(EList<TopLevelSimpleType> value);
	boolean validateComplexType(EList<TopLevelComplexType> value);
	boolean validateGroup2(EList<NamedGroup> value);
	boolean validateAttributeGroup(EList<NamedAttributeGroup> value);
	boolean validateElement(EList<TopLevelElement> value);
	boolean validateAttribute(EList<TopLevelAttribute> value);
	boolean validateNotation(EList<NotationType> value);
	boolean validateAnnotation1(EList<AnnotationType> value);
	boolean validateAttributeFormDefault(FormChoice value);
	boolean validateBlockDefault(Object value);
	boolean validateElementFormDefault(FormChoice value);
	boolean validateFinalDefault(Object value);
	boolean validateId(String value);
	boolean validateTargetNamespace(String value);
	boolean validateVersion(String value);
}
