/**
 *
 * $Id$
 */
package org.w3._2001.xml.xsd.validation;

import org.w3._2001.xml.xsd.ListType;
import org.w3._2001.xml.xsd.RestrictionType1;
import org.w3._2001.xml.xsd.UnionType;

/**
 * A sample validator interface for {@link org.w3._2001.xml.xsd.SimpleType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SimpleTypeValidator {
	boolean validate();

	boolean validateRestriction(RestrictionType1 value);
	boolean validateList(ListType value);
	boolean validateUnion(UnionType value);
	boolean validateFinal(Object value);
	boolean validateName(String value);
}
