/**
 *
 * $Id$
 */
package technology.ecoa.cross.platforms.view._2.validation;

import org.eclipse.emf.common.util.EMap;

import org.eclipse.emf.ecore.util.FeatureMap;

import technology.ecoa.cross.platforms.view._2.UseType;
import technology.ecoa.cross.platforms.view._2.View;

/**
 * A sample validator interface for {@link technology.ecoa.cross.platforms.view._2.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateXMLNSPrefixMap(EMap<String, String> value);
	boolean validateXSISchemaLocation(EMap<String, String> value);
	boolean validateUse(UseType value);
	boolean validateView(View value);
}
