/**
 *
 * $Id$
 */
package technology.ecoa.cross.platforms.view._2.validation;

import org.eclipse.emf.common.util.EList;

import technology.ecoa.cross.platforms.view._2.SpecificBindingType;

/**
 * A sample validator interface for {@link technology.ecoa.cross.platforms.view._2.EUIDsBinding}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EUIDsBindingValidator {
	boolean validate();

	boolean validateSpecificBinding(EList<SpecificBindingType> value);
	boolean validateBoundToLinkId(String value);
	boolean validateEUIDs(String value);
}
