/**
 *
 * $Id$
 */
package technology.ecoa.logicalsystem._2.validation;

import technology.ecoa.logicalsystem._2.LatencyType1;
import technology.ecoa.logicalsystem._2.ThroughputType1;

/**
 * A sample validator interface for {@link technology.ecoa.logicalsystem._2.LinkType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LinkType1Validator {
	boolean validate();

	boolean validateThroughput(ThroughputType1 value);
	boolean validateLatency(LatencyType1 value);
	boolean validateFrom(String value);
	boolean validateId(String value);
	boolean validateTo(String value);
}
