/**
 *
 * $Id$
 */
package technology.ecoa.logicalsystem._2.validation;

import org.eclipse.emf.common.util.EList;

import technology.ecoa.logicalsystem._2.LinkType1;

/**
 * A sample validator interface for {@link technology.ecoa.logicalsystem._2.LogicalComputingNodeLinks}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LogicalComputingNodeLinksValidator {
	boolean validate();

	boolean validateLink(EList<LinkType1> value);
}
