/**
 *
 * $Id$
 */
package technology.ecoa.implementation._2.validation;

import technology.ecoa.implementation._2.ReceiversType;
import technology.ecoa.implementation._2.SendersType;

/**
 * A sample validator interface for {@link technology.ecoa.implementation._2.EventLink}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EventLinkValidator {
	boolean validate();

	boolean validateSenders(SendersType value);
	boolean validateReceivers(ReceiversType value);
	boolean validateId(int value);
}
