/**
 *
 * $Id$
 */
package technology.ecoa.implementation._2.validation;

import technology.ecoa.implementation._2.PinfoType;
import technology.ecoa.implementation._2.PropertyValues;

/**
 * A sample validator interface for {@link technology.ecoa.implementation._2.ModuleInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleInstanceValidator {
	boolean validate();

	boolean validatePropertyValues(PropertyValues value);
	boolean validatePinfo(PinfoType value);
	boolean validateImplementationName(String value);
}
