/**
 *
 * $Id$
 */
package technology.ecoa.implementation._2.validation;

import technology.ecoa.implementation._2.ProgrammingLanguage;

/**
 * A sample validator interface for {@link technology.ecoa.implementation._2.OpRefExternal}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OpRefExternalValidator {
	boolean validate();

	boolean validateLanguage(ProgrammingLanguage value);
	boolean validateOperationName(String value);
}
