/**
 *
 * $Id$
 */
package technology.ecoa.implementation._2.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import technology.ecoa.implementation._2.OpRef;
import technology.ecoa.implementation._2.OpRefActivatableFifo;
import technology.ecoa.implementation._2.OpRefActivatingFifo;

/**
 * A sample validator interface for {@link technology.ecoa.implementation._2.ReceiversType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReceiversTypeValidator {
	boolean validate();

	boolean validateGroup(FeatureMap value);
	boolean validateService(EList<OpRef> value);
	boolean validateReference(EList<OpRef> value);
	boolean validateModuleInstance(EList<OpRefActivatableFifo> value);
	boolean validateDynamicTrigger(EList<OpRefActivatingFifo> value);
}
