/**
 *
 * $Id$
 */
package technology.ecoa.uid._2.validation;

import org.eclipse.emf.common.util.EList;

import technology.ecoa.uid._2.ID;

/**
 * A sample validator interface for {@link technology.ecoa.uid._2.IDMap}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IDMapValidator {
	boolean validate();

	boolean validateID(EList<ID> value);
}
