/**
 *
 * $Id$
 */
package technology.ecoa.interface_._2.validation;

import org.eclipse.emf.common.util.EList;

import technology.ecoa.interface_._2.EEventDirection;
import technology.ecoa.interface_._2.Parameter;

/**
 * A sample validator interface for {@link technology.ecoa.interface_._2.Event}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EventValidator {
	boolean validate();

	boolean validateInput(EList<Parameter> value);
	boolean validateDirection(EEventDirection value);
}
