<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="edtlogical" nsURI="edtlogical" nsPrefix="edtlogical">
  <eClassifiers xsi:type="ecore:EClass" name="LogicalSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FileNamePrefix" lowerBound="1"
        eType="ecore:EDataType ../../com.dassault.ecoa.model/model/logicalSystem.ecore#//NameId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicalComputingPlatforms"
        lowerBound="1" upperBound="-1" eType="#//LogicalComputingPlatform" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicalComputingPlatformLinks"
        upperBound="-1" eType="#//LogicalComputingPlatformLink" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType ../../com.dassault.ecoa.model/model/logicalSystem.ecore#//NameId">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalComputingPlatform">
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicalComputingNodes"
        upperBound="-1" eType="#//LogicalComputingNode" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="logicalComputingNode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicalComputingNodeLinks"
        upperBound="-1" eType="#//LogicalComputingNodeLink" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="logicalComputingNodeLinks"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eLIPlatformId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//UnsignedInt"
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&#xA;          Define the Id to be used as Logical ELI Platform ID&#xA;          in the ELI generic header&#xA;        "/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="ELIPlatformId"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType ../../com.dassault.ecoa.model/model/logicalSystem.ecore#//NameId">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalComputingPlatformLink">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType ../../com.dassault.ecoa.model/model/logicalSystem.ecore#//NameId">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="throughputMegaBytesPerSecond"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latencyMicroSeconds" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//LogicalComputingPlatform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//LogicalComputingPlatform"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TransportBindingParameters"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TransportBindingProtocol"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalComputingNodeLink">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType ../../com.dassault.ecoa.model/model/logicalSystem.ecore#//NameId"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="throughputMegaBytesPerSecond"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latencyMicroSeconds" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//LogicalComputingNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//LogicalComputingNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalComputingNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicalProcessors" lowerBound="1"
        upperBound="-1" eType="#//LogicalProcessor" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EndianessType" lowerBound="1"
        eType="ecore:EEnum ../../com.dassault.ecoa.model/model/logicalSystem.ecore#//TypeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ModuleSwitchTimeMicroSeconds"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AvailableMemoryGigaBytes"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="osName" lowerBound="1"
        eType="ecore:EEnum ../../com.dassault.ecoa.model/model/logicalSystem.ecore#//NameType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="osVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ProtectionDomainLink" upperBound="-1"
        eType="ecore:EClass EDTDeployment.ecore#//ProtectionDomain" eOpposite="EDTDeployment.ecore#//ProtectionDomain/executeOnComputingNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalProcessor">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="logicalProcessors_._type"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="number"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="type"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StepDurationNanoSeconds"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="nanoSeconds"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
