<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="edtuid" nsURI="edtuid" nsPrefix="edtuid">
  <eClassifiers xsi:type="ecore:EClass" name="IDMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IDs" upperBound="-1" eType="#//ID"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ID">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Operation" lowerBound="1"
        eType="ecore:EClass EDTServices.ecore#//OperationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceLink" lowerBound="1"
        eType="ecore:EClass EDTProject2.ecore#//ServiceLink"/>
  </eClassifiers>
</ecore:EPackage>
