<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="edtudp" nsURI="edtudp" nsPrefix="edtudp">
  <eClassifiers xsi:type="ecore:EClass" name="UDPBinding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="platform" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../com.dassault.ecoa.model/model/UDPbinding.ecore#//PlatformType"
        containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="platform"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
