/**
 *
 * $Id$
 */
package technology.ecoa.sca.extension.scaExt.validation;

import technology.ecoa.sca.extension.scaExt.ImplementationType;

/**
 * A sample validator interface for {@link technology.ecoa.sca.extension.scaExt.Instance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InstanceValidator {
	boolean validate();

	boolean validateImplementation(ImplementationType value);
	boolean validateComponentType(String value);
	boolean validateVersion(String value);
}
