/**
 *
 * $Id$
 */
package technology.ecoa.module.behaviour._2.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import technology.ecoa.module.behaviour._2.Computing;
import technology.ecoa.module.behaviour._2.Loop;
import technology.ecoa.module.behaviour._2.OperationCall;

/**
 * A sample validator interface for {@link technology.ecoa.module.behaviour._2.ActionSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActionSetValidator {
	boolean validate();

	boolean validateGroup(FeatureMap value);
	boolean validateLoop(EList<Loop> value);
	boolean validateComputing(EList<Computing> value);
	boolean validateOperationCall(EList<OperationCall> value);
}
