/**
 *
 * $Id$
 */
package technology.ecoa.types._2.validation;

import org.eclipse.emf.common.util.EList;

import technology.ecoa.types._2.Field;

/**
 * A sample validator interface for {@link technology.ecoa.types._2.Record}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RecordValidator {
	boolean validate();

	boolean validateField(EList<Field> value);
	boolean validateComment(String value);
	boolean validateName(String value);
}
