/**
 *
 * $Id$
 */
package technology.ecoa.types._2.validation;


/**
 * A sample validator interface for {@link technology.ecoa.types._2.Simple}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SimpleValidator {
	boolean validate();

	boolean validateComment(String value);
	boolean validateMaxRange(Object value);
	boolean validateMinRange(Object value);
	boolean validateName(String value);
	boolean validatePrecision(Object value);
	boolean validateType(String value);
	boolean validateUnit(String value);
}
