/**
 *
 * $Id$
 */
package technology.ecoa.udpbinding._2.validation;

import org.eclipse.emf.common.util.EList;

import technology.ecoa.udpbinding._2.PlatformType;

/**
 * A sample validator interface for {@link technology.ecoa.udpbinding._2.UDPBindingType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UDPBindingTypeValidator {
	boolean validate();

	boolean validatePlatform(EList<PlatformType> value);
}
