/**
 *
 * $Id$
 */
package technology.ecoa.deployment._2.validation;

import org.eclipse.emf.common.util.EList;

import technology.ecoa.deployment._2.LogPolicy;
import technology.ecoa.deployment._2.PlatformConfiguration;
import technology.ecoa.deployment._2.ProtectionDomain;
import technology.ecoa.deployment._2.WireMapping;

/**
 * A sample validator interface for {@link technology.ecoa.deployment._2.Deployment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeploymentValidator {
	boolean validate();

	boolean validateProtectionDomain(EList<ProtectionDomain> value);
	boolean validateLogPolicy(EList<LogPolicy> value);
	boolean validatePlatformConfiguration(EList<PlatformConfiguration> value);
	boolean validateWireMapping(EList<WireMapping> value);
	boolean validateFinalAssembly(String value);
	boolean validateLogicalSystem(String value);
}
