/**
 *
 * $Id$
 */
package technology.ecoa.deployment._2.validation;

import java.math.BigDecimal;

import org.eclipse.emf.common.util.EList;

import technology.ecoa.deployment._2.ComputingNodeConfiguration;
import technology.ecoa.deployment._2.PlatformMessages;

/**
 * A sample validator interface for {@link technology.ecoa.deployment._2.PlatformConfiguration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PlatformConfigurationValidator {
	boolean validate();

	boolean validateComputingNodeConfiguration(EList<ComputingNodeConfiguration> value);
	boolean validatePlatformMessages(EList<PlatformMessages> value);
	boolean validateComputingPlatform(String value);
	boolean validateEUIDs(String value);
	boolean validateFaultHandlerNotificationMaxNumber(BigDecimal value);
}
