/**
 *
 * $Id$
 */
package technology.ecoa.insertion.policy._2.validation;

import org.eclipse.emf.common.util.EList;

import technology.ecoa.insertion.policy._2.ModulePINFOType;

/**
 * A sample validator interface for {@link technology.ecoa.insertion.policy._2.DefaultPINFO}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DefaultPINFOValidator {
	boolean validate();

	boolean validateModulePINFO(EList<ModulePINFOType> value);
}
