/**
 *
 * $Id$
 */
package technology.ecoa.insertion.policy._2.validation;

import org.eclipse.emf.common.util.EList;

import technology.ecoa.insertion.policy._2.InsertionPolicy;

/**
 * A sample validator interface for {@link technology.ecoa.insertion.policy._2.InsertionPolicyList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InsertionPolicyListValidator {
	boolean validate();

	boolean validateInsertionPolicy(EList<InsertionPolicy> value);
	boolean validateComponentImplementation(String value);
}
