/**
 *
 * $Id$
 */
package technology.ecoa.insertion.policy._2.validation;

import technology.ecoa.insertion.policy._2.TypeType1;

/**
 * A sample validator interface for {@link technology.ecoa.insertion.policy._2.LanguageLibrary}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LanguageLibraryValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateType(TypeType1 value);
	boolean validateVersion(String value);
}
