/**
 *
 * $Id$
 */
package technology.ecoa.insertion.policy._2.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import technology.ecoa.insertion.policy._2.LanguageLibraries;
import technology.ecoa.insertion.policy._2.ModuleCompilationOptions;
import technology.ecoa.insertion.policy._2.OSAPIType;

/**
 * A sample validator interface for {@link technology.ecoa.insertion.policy._2.ModuleDependencies}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleDependenciesValidator {
	boolean validate();

	boolean validateLanguageRuntime(EObject value);
	boolean validateLanguageLibraries(LanguageLibraries value);
	boolean validateDirectOSAccess(EList<OSAPIType> value);
	boolean validateModuleCompilationOptions(ModuleCompilationOptions value);
	boolean validateInstanceName(String value);
}
