/**
 *
 * $Id$
 */
package technology.ecoa.insertion.policy._2.validation;

import org.eclipse.emf.ecore.EObject;

import technology.ecoa.insertion.policy._2.DynamicMemoryType;

/**
 * A sample validator interface for {@link technology.ecoa.insertion.policy._2.ModuleMemoryUsage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleMemoryUsageValidator {
	boolean validate();

	boolean validateUserContextSize(EObject value);
	boolean validateWarmStartContextSize(EObject value);
	boolean validateDynamicMemory(DynamicMemoryType value);
	boolean validateStackSize(EObject value);
	boolean validateHeapSize(EObject value);
	boolean validateInstanceName(String value);
}
