/**
 *
 * $Id$
 */
package technology.ecoa.insertion.policy._2.validation;

import java.math.BigInteger;

/**
 * A sample validator interface for {@link technology.ecoa.insertion.policy._2.PeriodicActivationProfile}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PeriodicActivationProfileValidator {
	boolean validate();

	boolean validateDeadline(double value);
	boolean validatePeriod(double value);
	boolean validateRelativePriority(BigInteger value);
	boolean validateWcet(double value);
}
