/**
 *
 * $Id$
 */
package technology.ecoa.insertion.policy._2.validation;

import java.math.BigInteger;

import technology.ecoa.insertion.policy._2.IntegrityType;
import technology.ecoa.insertion.policy._2.QualityType;

/**
 * A sample validator interface for {@link technology.ecoa.insertion.policy._2.TransportProtocol}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransportProtocolValidator {
	boolean validate();

	boolean validateIntegrity(IntegrityType value);
	boolean validateMaxLatency(double value);
	boolean validateMinBandwidth(BigInteger value);
	boolean validateQuality(QualityType value);
}
