/**
 *
 * $Id$
 */
package technology.ecoa.interface_.qos._2.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import technology.ecoa.interface_.qos._2.Data;
import technology.ecoa.interface_.qos._2.Event;
import technology.ecoa.interface_.qos._2.RequestResponse;

/**
 * A sample validator interface for {@link technology.ecoa.interface_.qos._2.Operations}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationsValidator {
	boolean validate();

	boolean validateGroup(FeatureMap value);
	boolean validateData(EList<Data> value);
	boolean validateEvent(EList<Event> value);
	boolean validateRequestresponse(EList<RequestResponse> value);
}
