/**
 *
 * $Id$
 */
package technology.ecoa.interface_.qos._2.validation;

import technology.ecoa.interface_.qos._2.Operations;

/**
 * A sample validator interface for {@link technology.ecoa.interface_.qos._2.ServiceInstanceQoS}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServiceInstanceQoSValidator {
	boolean validate();

	boolean validateOperations(Operations value);
}
